# Use docker-based build environment (instead of openvz)
sudo: false

language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
  - mvn clean test jacoco:report coveralls:report
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml